-- V1 베이스라인 — 이슈 #399. 소유: 강희진
--
-- Hibernate ddl-auto=create 가 만들던 스키마를 그대로 옮긴 것이다. 손으로 지어내지 않았다:
-- @DataJpaTest(ddl-auto=create) 로 띄운 H2 에서 SCRIPT NODATA 로 뽑아 MEMORY 키워드·계정
-- 생성 같은 덤프 부산물만 걷어냈다. prod 는 ddl-auto=validate 라 이 파일과 엔티티가
-- 어긋나면 기동이 실패한다 — ProdPersistenceRestartTest 가 그 대조를 상시로 돈다.
--
-- ❗H2 문법이다(ENUM·CHARACTER LARGE OBJECT·IDENTITY). Postgres 로 옮길 때(RDS, 인프라
-- 단계) 이 파일을 그대로 쓸 수 없고 방언 검토가 필요하다.
--
-- 엔티티가 바뀌면 이 파일을 고치지 말고 V2__*.sql 을 추가한다 — 적용된 마이그레이션을
-- 고치면 Flyway 체크섬 검증이 기동을 거부한다(맞는 동작이다).

-- ── 세션 집합체 (core/session/Session — F-INT-001) ─────────────────────────────

CREATE TABLE sessions (
    id                    CHARACTER VARYING(255) NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    age_band              CHARACTER VARYING(255) NOT NULL,
    amount_band           CHARACTER VARYING(255),
    asked_types           CHARACTER VARYING,
    branch_id             CHARACTER VARYING(255),
    channel               ENUM('FACE_TO_FACE', 'MOBILE', 'TM') NOT NULL,
    coaching_score        INTEGER NOT NULL,
    contract_ref          CHARACTER VARYING(255),
    experience_level      CHARACTER VARYING(255),
    gate_rule_trace       CHARACTER VARYING,
    gate_rules_version    INTEGER NOT NULL,
    gate_signal           ENUM('GREEN', 'RED', 'YELLOW'),
    gate_unmeasured       INTEGER NOT NULL,
    input_ms              CHARACTER VARYING,
    judged_at             TIMESTAMP(6) WITH TIME ZONE,
    judgments_by_item     CHARACTER VARYING,
    override_approver     CHARACTER VARYING(255),
    override_decided_at   TIMESTAMP(6) WITH TIME ZONE,
    override_reason       CHARACTER VARYING(255),
    override_status       ENUM('APPROVED', 'NONE', 'PENDING_APPROVAL') NOT NULL,
    product_id            CHARACTER VARYING(255) NOT NULL,
    repeated_answer_items CHARACTER VARYING,
    seller_id             CHARACTER VARYING(255),
    state                 ENUM('ABORTED', 'CLOSED', 'CREATED', 'IN_PROGRESS', 'JUDGED', 'RE_EXPLAIN', 'RE_VERIFY') NOT NULL,
    suitability_status    ENUM('MISMATCH', 'NOT_EVALUATED', 'NO_MISMATCH', 'UNKNOWN') NOT NULL,
    survey_result         CHARACTER VARYING,
    survey_schema_version CHARACTER VARYING(255),
    vulnerable            BOOLEAN NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

-- @ElementCollection 4벌 — 항목(item_id) 단위 맵이라 (session_id, item_id) 복합 PK 다.

CREATE TABLE session_reverify (
    session_id     CHARACTER VARYING(255) NOT NULL,
    item_id        CHARACTER VARYING(255) NOT NULL,
    reverify_count INTEGER,
    CONSTRAINT pk_session_reverify PRIMARY KEY (session_id, item_id),
    CONSTRAINT fk_session_reverify_session FOREIGN KEY (session_id) REFERENCES sessions(id)
);

CREATE TABLE session_utterance (
    session_id  CHARACTER VARYING(255) NOT NULL,
    item_id     CHARACTER VARYING(255) NOT NULL,
    masked_text CHARACTER VARYING,
    CONSTRAINT pk_session_utterance PRIMARY KEY (session_id, item_id),
    CONSTRAINT fk_session_utterance_session FOREIGN KEY (session_id) REFERENCES sessions(id)
);

CREATE TABLE session_asked_question (
    session_id CHARACTER VARYING(255) NOT NULL,
    item_id    CHARACTER VARYING(255) NOT NULL,
    question   CHARACTER VARYING,
    CONSTRAINT pk_session_asked_question PRIMARY KEY (session_id, item_id),
    CONSTRAINT fk_session_asked_question_session FOREIGN KEY (session_id) REFERENCES sessions(id)
);

CREATE TABLE session_asked_source (
    session_id CHARACTER VARYING(255) NOT NULL,
    item_id    CHARACTER VARYING(255) NOT NULL,
    source     ENUM('DISPLAYED', 'REVERIFY', 'SERVER_FALLBACK', 'TEMPLATE_FALLBACK'),
    CONSTRAINT pk_session_asked_source PRIMARY KEY (session_id, item_id),
    CONSTRAINT fk_session_asked_source_session FOREIGN KEY (session_id) REFERENCES sessions(id)
);

-- ── append-only 불변 기록 (evidence/ — F-GTE-004·F-CMN-002, ADR-003) ───────────
-- BaseEntity 를 상속하지 않으므로 created_at/updated_at 이 없다 — UPDATE 경로가 없는
-- 테이블이라 그게 맞다(EvidenceEntry 주석).

CREATE TABLE evidence_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    stream       CHARACTER VARYING(255) NOT NULL,
    seq          BIGINT NOT NULL,
    prev_hash    CHARACTER VARYING(64) NOT NULL,
    hash         CHARACTER VARYING(64) NOT NULL,
    payload_json CHARACTER LARGE OBJECT NOT NULL,
    CONSTRAINT pk_evidence_entries PRIMARY KEY (id),
    -- 같은 자리 이중 적재는 코드 결함이고 DB 가 거절해야 한다(EvidenceEntry 주석).
    CONSTRAINT uk_evidence_stream_seq UNIQUE (stream, seq)
);

CREATE TABLE evidence_stream_anchors (
    stream    CHARACTER VARYING(255) NOT NULL,
    head_hash CHARACTER VARYING(64) NOT NULL,
    count     BIGINT NOT NULL,
    CONSTRAINT pk_evidence_stream_anchors PRIMARY KEY (stream)
);
